export const data = [
  {
    id: 1,
    name: "johnd",
    age: 12,
    email: "john@gmail.com",
    address: "kilcoole",
    phone: "1-567-094-1345",
    completed: true,
  },

  {
    id: 2,
    name: "Leanne Graham",
    age: 19,
    email: "Sincere@april.biz",
    address: "Gwenborough",
    phone: "92998-3874",
    completed: false,
  },
  {
    id: 3,
    name: "Ervin Howell",
    age: 20,
    email: "Shanna@melissa.tv",
    address: "Wisokyburgh",
    phone: "90566-7771",
    completed: true,
  },
  {
    id: 4,
    name: "Clementine Bauch",
    age: 22,
    email: "Nathan@yesenia.net",
    address: "McKenziehaven",
    phone: "59590-4157",
    completed: false,
  },
  {
    id: 5,
    name: "Patricia Lebsack",
    age: 23,
    email: "Julianne.OConner@kory.org",
    address: "South Elvis",
    phone: "53919-4257",
    completed: true,
  },
  {
    id: 6,
    name: "Chelsey Dietrich",
    age: 18,
    email: "Lucio_Hettinger@annie.ca",
    address: "Roscoeview",
    phone: "(254)954-1289",
    completed: false,
  },
  {
    id: 7,
    name: "Mrs. Dennis Schulist",
    age: 17,
    email: "Karley_Dach@jasper.info",
    address: "South Christy",
    phone: "23505-1337",
    completed: false,
  },
  {
    id: 8,
    name: "Kurtis Weissnat",
    age: 25,
    email: "Telly.Hoeger@billy.biz",
    address: "Howemouth",
    phone: "58804-1099",
    completed: false,
  },
  {
    id: 9,
    name: "Nicholas Runolfsdottir V",
    age: 22,
    email: "Sherwood@rosamond.me",
    address: "Aliyaview",
    phone: "586.493.6943 x140",
    completed: true,
  },
  {
    id: 10,
    name: "Glenna Reichert",
    age: 23,
    email: "Chaim_McDermott@dana.io",
    address: "Bartholomebury",
    phone: "76495-3109",
    completed: true,
  },
  {
    id: 11,
    name: "Clementina DuBuque",
    age: 24,
    email: "Rey.Padberg@karina.biz",
    address: "Lebsackbury",
    phone: "31428-2261",
    completed: false,
  },
];
